apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # baseを参照する
  - ../../base
# baseのリソースに対してパッチを適用する
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: todo-api
    spec:
      # dev環境ではレプリカを1つに削減
      replicas: 1
  target:
    kind: Deployment
    name: todo-api
- patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: todo-frontend
      spec:
        # dev環境ではレプリカを1つに削減
        replicas: 1

  target:
    kind: Deployment
    name: todo-frontend
