apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db
  labels:
    app: todo-db
spec:
  # DBはシングルインスタンス
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
      - name: todo-db
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "tododb"
        - name: POSTGRES_USER
          value: "todouser"
        - name: POSTGRES_PASSWORD
        # あとでSecretに変更する
          value: "todopassword"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          exec:
            # PostgreSQLが接続を受け付けられる状態かを確認
            command:
            - pg_isready
            - -U
            - todouser
            - -d
            - tododb
          initialDelaySeconds: 10
          periodSeconds: 5
