apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: todo-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}
