---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-db-secret
  namespace: todo-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCpo3r6qKJ3+xZqi9EPCFpcwthHqfwtdNB0t8kES6UrkbDGtq1k6lrrt3F+7eIqt0Ro8JuePmToG6ZgOqO5NWontOB+8ApUuuubhRYrl1bIM1ZDvvGQiCA1ZR7f8v1kEuaT2KAkPPU2Tb3JnXEQoLQrt7hL3/6r9sFzSBIf3uti0EFKWb+vEOFjlb69KF9Ay3pT9MpJN9zgZ0rpHmUUdPt3ujOBYzUa47WoCwTPs9CxlNRhHE1aUWChCX3kiqB6z1ucoPE6b/67X9WUrGosErXgKkrNQtNKrh0Mq3ow23gGew0WZdJbE9Mu5sMox/+wrk06cfVSIJ8saQ23cK+pIg7dL/Qg3QS1rVqOVjUhw0834371JUpe6H7vkkGbunuMVW6D0GCpNtPKsE6+4ea1MrxYr/e32GW1caX86O4ww0PMVw6DS64/aThU158QNpjysLtPixivC7OjFOQaoxYCxB73oiRFAfKX+cf6IeIkD0i8SQot7QDzlYi8LnUAaxeBXiP7PDk3MBZhic+3yE2JhmzvL6XrbqvP5W8XyItQDjJJY38DazS7MSHyu9R1dBfk2CCcxC0q7IkIIE5a81JMFgEDwxry/zbgg7gKyVRw49bBV2QEh4A8CVnQKoCYyoqKEW5SMT6LAPplO4n94UR2VSATpozmnWZCL3KLAm2x2Bp7XZshPz/Pcudz4LWyyru2ngtgPD14p+so2Q==
    POSTGRES_USER: AgAlcO+kwNwXFNpO3sO2uPANo+Lgf5SX7aYpmS5eGwAEeLsHhaW6tj12ZPppbUMkAzHnzYunutrVWMGr1a9jE+gYZWpjPj1zJxYKVNXpRHhL/MtD4+gIiJTFD10s1acUuGc5JbBxdgShRaHQFWu8v3nrW11Y6nPicec6XNoKgB5/4V5D7xDaHSSTVxWNCEzVkkUvHT94KBoNOSxiySTm37ECX6s/zVyeDm8ZN9nIWZ1ZxPyyoJav/HyB8mfUvtPHLGjY7RHRvAEqljSQq6VVVmrKQwJRlsfRKXVvRt5S89M3udWZL44TJTCnDzmakNvhkJt1DMIavkAi0hHEDIVhYrLMUdzMgp0R0juTX3mZJmxNAOsQANtXdRqI9Y2HDP9KGZUmRnXXDwYfPAeCc3uINVdPA80Ml5gahdvtqSxc72sZ1Pwl9X4Fu8UDpk6wG28e0HJ+ALX5BeEQuixygPijrAC+Y4fBOrCznwA0+k+KuHFTxu60CUpt3Ycx/mu5Xr7WQjhowX5cRXBnDxKjXDTwwaPfds5ufrN+xoRyLZqBrtW/siaGzzWjzYEgLHeHyIoMXplSQ+UySWtDMOUXCHQ8rgfim/ySUP9jPKH2CMWMqWIOdect3ey1kYwrmKNq87uylBoSN//9M47QI0ptMKwST8wo1O70rfWUk2EiNjhiXpIVBnmCfOH4F6P0MH87gcmX6bolNCx8trksBw==
  template:
    metadata:
      name: todo-db-secret
      namespace: todo-app
    type: Opaque
