---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-db-secret
  namespace: todo-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC67VE5dfAtY9BZ6YV/Ap9AWfVqQQHQ5LkYAUvhmPGwdXK7iR1/cs082EAXoZA6PP+M6v1KKgam5CAtoM7fjrqB0MaBcUMvAO2930UHbbNNmRmmz4flUkaUo1L4vbqRjcJt2eVljhqaMx512NkD/7l6L6x/tqR/nfgPbGEFCBq1iRhntVTji1VNZTGJ9UUnpGMhZ7tJGuS1i8q3yjb+RA5p/3FRCCDOUqMnXPs8JD5VPJHIRACfvs0QuyMzaWZJdenCSvf6gyJG+OxS8fFfbkWL/AB26ajAB3YoeVjeObh7eEpKSeluULGCxBCCOvBUd6TuJdRdY9TbOjRx0YR9vghXshAiI+Jlbmrnu+uiJC4mBxMkZV+Vf/TjTNaLbE+x0u/untSGSjSkvP5t8eFbbOg5F6w3nO0LyhtGmKB7Z9z/0KjpKEE/elR52mfw9lDxDPKGB5EgQ6Vw3RUA5R6rUjbPkO3lWugCPSnO7KgBIBMJXyD0u9HQa99RtvgcPiGVMczCjHL1ZymVbKLrz5Yph7putNLJ7Q2Aql2Sv1IUtDc1r8bneLaaeZr1hmNcAQNQghuqv0LAJgrzTx2hkAeS5ESEjfnTqSBLr9/mJk/iV8GqSgcWFxQ6fgpPhf5uryqJ9uTZmLo91w5xVk5hbXXXImrmnbRv5xM+BErS7yWH9FFTzQ81c4HFelJCkd7WJq6+vXAajOFRNJ0B6w==
    POSTGRES_USER: AgAriEJyidWlzog1NYhJdFR+XIXv+jFEeMmcTtIJi/BStpVafye83t1Px8+n5El+kG1On5YxJ/sFYeiwvnYAXcwcbD5EuRHfd3A0dNI5q+cdEbaOd0Mu8uLX4WUiKmuNwyQrJahvTP3u0XR9IikNsDk5Gw7xuc/RQ+yCDeEZ9fMNtXrncscZ97oWRynuhzWYmx86lqHJrh58EorIvovt6mfeg7DOr6eI8qKRNzt8ZQcALmL/wLnO4MmqMy3qp+nEXqRwym0zYPASSekADaFbuU1GfN8rr6k+EClb2JHC/PmYHDVL29nXudP9qahqTr6pXy+AyPHRlzoCiI+j1wcXAEuTmT1610dB6tdd8PBrtMTBqHdwStl8glsx7sIHIoMfwNLRcD8X7XP4n/hP6EKSKujtqeTMLgllGXQuw4EXWvWcFT89YD1LT81hEVZN4LbQtQKKFWcmTN5wMDbBMz3DuDgVBx6WnlcoibWc0at3zI1/yFhBNdax/IkmM0wtx8XF/kiCckq1n+tBWx8xwdCzl0uEnbnvkfg0xaHw6Gk2Mxybi4Cb+Gx0FpQr0xNBRUKX/9zI9f1gVYIlfnG9F5ov6kLLeZQ4axBI7Rxor7tKaQ9cq49EG2M3GRE5bPzzuHx0KZNDu+XnaMwhDAZPAcKD3z+JI1aOUFX7fWDzUkuYdpvCFLQxgeE/DbtXZ6T0aAr2l8t9wGctTFRCew==
  template:
    metadata:
      name: todo-db-secret
      namespace: todo-app
    type: Opaque
