---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-db-secret
  namespace: todo-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAYOAHhoHO3rDHrW+n7u/ETQuTz1sq9aSlkbATlLOyMrY4z8d1v04hTfvFo2xsEJfmEe9j5Un10WkC1ZkZCq2f8xln4tKU1jSik9mYvVjy7SHiMT4vyR0q4CWZbnIAqgOlNxYOVm20Jij4c1auN8+mUh+mQ1rdFLOYWqZPK8de37cZTGfOzg01/Xda0pZm8Ir9U+B6Fp3m9w257dhD9wOvMXdiOxKF8X3fmot4gTs/lk0oi4xOA04eG38Qv1DCq0mBhR+Gh3FAK5N6LkmsKQbvRygr9PjstfzZS3i0M5cjPCXgzad5/wpHbKcsrBHP8zCshggqxwCW0UGSY3H+/WDSMzELnx9zSO5nluzEbWe3fLlgBB5eo5S4XEpyjTP+yfMB2X6mR097HzY9fXkImSd0uddSISw8yRe+Wan5ueR5CchmC7plMukhBfMw+iy3w+cFHLbaTOhnZ29WSf/oxSotWtMf/vr2+m75WfYJkcyvfrk735z6D3NnKyPBLcvlUsZRU0n8sk27nSfUHiNfhBODSdkD7NNHsYlm4pfgCMzis62UyPtXRUgLYsU83szvBQtXcn6yc+fUy3it+QLLLEVmkpoGaUM01QEr01V4GLFGOVMj6UAln0GaM3iO5kevOwHJItozSMGO15TPWH23LQ6bKMv6ovnOTn2vU0LpGI325+FKJMmeUi/gQXFZdNWsWkCI/jxPYQlw3FIQqJWFoBS+EMWd3gEbY
    POSTGRES_USER: AgBoQqSRcZc3WuZLZpda4WzyEpd/9BRUABefPaDXYC9oc6cdmQVDvH7BBSuYuQWoJFB59w45EkhXUOxbzpzD7EqyL7QG8cfNSJzDAZy2AmecQ2mlTUtjm5KimA9l+5ITpdicNKO7XYu5OfSUVr9ZmzeIMfGtZxUL8GT7yINxEAKnEKE3dqc2oFbVRP+xaEwB6FgGiJ1A4YY0Seryd00YCpV27viONQn6X0rkXeo8TvquPgNNMzAXB24QRhW2+J2wQes9mnDnoVjgToIE777R2ZEWvB1q8wm8dIQaNAe122m4pxhJovw+OqUmyeqHrXrxJdRGBhNU6q5N25GNAeFLjAw1nsIoeb/ao1APRk34oCEAckoUDrz6kxHQyCK1PYUuWMJoX6/xnjFo1+IC8GHO/CaR77VxWzM5k9PLgde2X0xhIKmworTstt9RkxBEGaxv+44tJ4YQZPXaG3aOjrMtYuBo1MIEmZ1w7WBqIKmn4LkKadFAcf47oP2xOwAIzri/rBWtWZBNeK3WVnBhee2R6jBgSpLZhxP0xwmqJ+4bpzjrih1jn3laKlrpvlS31qjZqZSV5xTkN+EtAjPb3EEvxQUycIJDsu3JjaNLqnh3aQllINMoT9+mT2mDN0Xmw8iGt1GshtluQtQCN3TNsQEM6Df4zn/V0agjbUSqi4oENlR6F/5VXBxVS4/7S8rgruZPylkpWbUVl0xK+w==
  template:
    metadata:
      name: todo-db-secret
      namespace: todo-app
    type: Opaque
