apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.credentials.username }}
  POSTGRES_PASSWORD: {{ .Values.db.credentials.password }}
