apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: {{ .Values.namespace }}
  labels:
    app: todo-api
spec:
  selector:
    app: todo-api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: todo-frontend
spec:
  selector:
    app: todo-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: todo-db
  namespace: {{ .Values.namespace }}
  labels:
    app: todo-db
spec:
  selector:
    app: todo-db
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
      protocol: TCP
  type: ClusterIP
