apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-frontend
spec:
  type: {{.Values.frontend.service.type}}
  selector:
    app: {{.Release.Name}}-frontend
  ports:
    - port: {{.Values.frontend.service.port}}
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-api
spec:
  selector:
    app: {{.Release.Name}}-api
  ports:
    - port: {{.Values.api.service.port}}
      targetPort: {{.Values.api.service.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-db
spec:
  selector:
    app: {{.Release.Name}}-db
  ports:
    - port: {{.Values.db.service.port}}
      targetPort: {{.Values.db.service.port}}
